---
- name: install nginx
  apt: name=nginx state=present
  tags: nginx

- name: Delete previous template files
  file: >
    path="{{item}}"
    state=absent
  with_items:
    - "{{ nginx_path }}/sites-enabled/default"
    - "{{ nginx_path }}/sites-available/default"
  notify: restart nginx
  tags: nginx

- name: Template nginx conf
  template: src=default.conf.j2 dest={{ nginx_path }}/nginx.conf
  notify: restart nginx
  tags: nginx

- name: Expose certbot well-known
  template:
    src: http.conf.j2
    dest: "{{ nginx_path }}/sites-enabled/http.conf"
  notify: restart nginx
  tags: nginx

- meta: flush_handlers
