---
- name: Install httplib2
  apt: name=python-httplib2 state=present
  tags: [ create, elasticsearch, index ]

- wait_for:
    port: 9200
    host: localhost
    timeout: 300

- name: Create index template
  run_once: true
  uri:
    method: PUT
    url: "http://localhost:9200/_template/logstash"
    body: "{{ lookup('file', 'logstash-apiparticulier.mapping.json') }}"
    HEADER_Content-Type: "application/json"
    body_format: json
    return_content: yes
  register: es_template_creation_result
  changed_when: es_template_creation_result.status == 200
  failed_when: not (es_template_creation_result.status == 200 or (es_template_creation_result.status == 400 and ("IndexAlreadyExistsException" in es_template_creation_result.json.error)))
  tags: [ create, elasticsearch, index ]

- name: debug
  debug: var=es_template_creation_result
  tags: [ create, elasticsearch, index ]
