---
- name: Ensure user deploy
  user:
    name: deploy

- name: install yarn globally
  tags:
    - yarn
  shell: npm install --global yarn

- name: ensure apps directory
  file:
    state: directory
    mode: 0777
    path: /opt/apps

- name: create app directory for svair-mock
  file:
    state: directory
    mode: 0775
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    path: /opt/apps/svair-mock

- name: create configuration directory for svair-mock
  file:
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0775
    path: /etc/svair-mock

- name: write configuration for svair-mock
  template:
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0664
    src: svair-mock.conf.j2
    dest: /etc/svair-mock/svair-mock.conf

- name: create systemd service for SVAIR Mock
  template:
    owner: root
    group: root
    mode: 0644
    src: svair-mock.service.j2
    dest: /etc/systemd/system/svair-mock.service
  register: svair_mock_unit

- name: reload systemd daemon
  shell: systemctl daemon-reload
  when: svair_mock_unit.changed

- name: install yarn globaly
  shell: npm install yarn -g

- name: restarts svair mock
  service:
    name: svair-mock
    state: restarted
