---
- name: Stop the service before installing node_modules
  become: yes
  service:
    name: "{{ application_to_deploy }}"
    state: stopped

- name: Install node dependencies
  become: yes
  become_user: vagrant
  # For some reason, the ansible official npm module fails at installing the dependencies here, so we do it manually
  shell: npm ci
  args:
    executable: /bin/bash
    chdir: "/opt/apps/{{ application_to_deploy }}/current"
    creates: "/opt/apps/{{ application_to_deploy }}/current/node_modules"

- name: Start the service
  become: yes
  service:
    name: "{{ application_to_deploy }}"
    state: started
