---
- name: install dependencies
  apt:
    name:
      - openssl
      - libpcre3
      - procps
      - perl
    update_cache: true

- name: get and install Kong package
  apt:
    deb: https://bintray.com/kong/kong-deb/download_file?file_path=kong-2.0.1.xenial.amd64.deb

- name: configure kong
  template:
    src: kong.conf.j2
    dest: /etc/kong/kong.conf

- name: configure kong applications
  template:
    src: kong.yml.j2
    dest: /etc/kong/kong.yml

- name: copy kong auth plugin
  unarchive:
    src: "https://codeload.github.com/betagouv/api-particulier/tar.gz/master"
    remote_src: yes
    dest: /root
    extra_opts:
      - "api-particulier-master/kong-delegateAuth"
      - "--strip-components=1"

- name: install kong plugins
  shell: |
    cd /root/kong-delegateAuth
    luarocks make

- name: install apache2 utils
  apt:
    name: apache2-utils
    update_cache: true

- name: set authorized nginx users
  shell: >
    htpasswd -b -c /etc/nginx/htpasswd.users {{ item.name }} {{ item.password }}
  with_items: "{{ kong_users }}"

- name: create systemd service for Kong
  template:
    owner: root
    group: root
    mode: 0644
    src: kong.service.j2
    dest: /etc/systemd/system/kong.service

- name: enable kong service
  systemd:
    name: kong
    enabled: yes
    daemon_reload: yes
    state: restarted
