---
- name: create certificate directory for nginx
  file:
    path: /etc/nginx/ssl
    state: directory

- name: copy cert
  copy:
    src: certificates/{{ api_particulier_environment }}/api-particulier.crt
    dest: /etc/nginx/ssl/particulier.apps.crt
  notify: "restart web services"

- name: copy cert key
  copy:
    src: certificates/{{ api_particulier_environment }}/api-particulier.key
    dest: /etc/nginx/ssl/particulier.apps.key
  notify: "restart web services"

- name: copy ca cert
  copy:
    src: certificates/{{ api_particulier_environment }}/api-particulier-CA.pem
    dest: /etc/nginx/ssl/particulier.apps-CA.crt
  notify: "restart web services"
