backend:
  name: github
  repo: betagouv/svair-mock

media_folder: public/media

show_preview_links: false

collections:
  - name: "people"
    label: "Déclarant"
    description: "Personnes présentes sur l'avis d'imposition"
    folder: "data/people"
    create: true
    extension: json
    format: json
    identifier_field: "id"
    slug: "{{id}}_{{surname}}-{{name}}"
    summary: "{{name}} {{surname}} né(e) le {{birthdate}}"
    editor:
      preview: false
    fields:
      - label: "ID"
        name: "id"
        widget: "id"
        required: true
      - label: "Nom de famille"
        name: "surname"
        widget: "string"
        required: true
      - label: "Nom de naissance"
        name: "birthname"
        widget: "string"
        required: true
      - label: "Prénom"
        name: "name"
        widget: "string"
        required: true
      - label: "Date de naissance"
        name: "birthdate"
        widget: "date"
        format: "DD/MM/YYYY"
        required: true
  - name: "addresses"
    label: "Adresse"
    description: "Adresses fiscales"
    folder: "data/addresses"
    create: true
    extension: json
    format: json
    identifier_field: "id"
    slug: "{{id}}_{{line1}}-{{zipCode}}-{{city}}"
    summary: "{{line1}} {{zipCode}} {{city}}"
    editor:
      preview: false
    fields:
      - label: "ID"
        name: "id"
        widget: "id"
        required: true
      - label: "Numéro et nom de voie"
        name: "line1"
        widget: "string"
        required: true
      - label: "Code postal"
        name: "zipCode"
        widget: "string"
        required: true
      - label: "Commune"
        name: "city"
        widget: "string"
        required: true
  - name: "notices"
    label: "Avis"
    description: "Liste des avis requêtables"
    folder: "data/notices"
    create: true
    extension: json
    format: json
    identifier_field: "notice_number"
    slug: "{{tax_number}}_{{notice_number}}-{{taxYear}}"
    summary: "{{tax_number}}-{{notice_number}} {{taxYear}}"
    editor:
      preview: false
    fields:
      - label: "Numéro fiscal"
        name: "taxNumber"
        widget: "tax-number"
        required: true
      - label: "Numéro d'avis"
        name: "noticeNumber"
        widget: "notice-number"
        required: true
      - label: "Déclarant 1"
        name: "person1"
        widget: "relation"
        required: true
        collection: "people"
        searchFields:
          - "surname"
          - "birthname"
          - "name"
        displayFields:
          - "surname"
          - "name"
        valueField: "id"
      - label: "Déclarant 2"
        name: "person1"
        widget: "relation"
        collection: "people"
        searchFields:
          - "surname"
          - "birthname"
          - "name"
        displayFields:
          - "surname"
          - "name"
        valueField: "id"
      - label: "Adresse"
        name: "address"
        widget: "relation"
        required: true
        collection: "addresses"
        searchFields:
          - "line1"
          - "zipCode"
          - "city"
        displayFields:
          - "line1"
          - "zipCode"
          - "city"
        valueField: "id"
      - label: "Année d'imposition"
        name: "taxYear"
        widget: "number"
        valueType: "int"
        required: true
        min: 2000
        max: 3000
