- name: ensure that config file are loaded after interface definition
  lineinfile:
    path: /etc/network/interfaces
    line: 'source /etc/network/interfaces.d/*.cfg'
  notify: flush networking
  when: "api_particulier_environment == 'development'" # there is a difference between the bento box and the ovh box

- name: copy interfaces.d config
  template:
    src: templates/interfaces.d.cfg.j2
    dest: /etc/network/interfaces.d/60-alternate-ips.cfg
  notify: flush networking

- name: install iptables-persistent
  apt:
    name: iptables-persistent

- name: reset POSTROUTING rules
  shell: iptables -F POSTROUTING -t nat
  notify: persist iptables

# We want to choose randomly the ip used for outgoing calls.
# As the iptables rules randomness are independent experiments, for 3 ips we want:
# 1. the first ip to have 1 chance on 3 to be chosen
# 2. the second ip to have 1 chance on 2 to be chosen
# 3. the last ip to have 1 chance on 1 to be chosen
# By doing so, we are sure that each ips have a 33% chance to be chosen.
- name: outgoing load balancing for apps
  shell: iptables -t nat -o {{ main_network_interface }} -A POSTROUTING -j SNAT --to-source {{ item.1 }} -m statistic --mode random --probability {{ 1 / ((load_balancing_ips[inventory_hostname] | length) - item.0) }}
  with_indexed_items: "{{ load_balancing_ips[inventory_hostname] }}"
  notify: persist iptables
