---
- name: create certificate directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/pki/client
    - /etc/pki/ca

- name: copy chain certificate
  copy:
    src: certificates/{{ api_particulier_environment }}/monitoring.crt
    dest: /etc/pki/client/cert.pem

- name: copy encrypted keys
  copy:
    src: certificates/{{ api_particulier_environment }}/monitoring.key
    dest: /etc/pki/client/cert.key

- name: copy CA
  copy:
    src: certificates/{{ api_particulier_environment }}/monitoring-CA.pem
    dest: /etc/pki/ca/ca.crt

- name: decrypt certificate
  shell: >
    openssl pkcs8 -topk8 -in /etc/pki/client/cert.key -out /etc/pki/client/cert.pkcs8 -nocrypt
