_format_version: "1.1"

services:
  - name: api-particulier
    url: http://api-particulier:3004
    routes:
      - name: api
        paths:
          - /
    plugins:
      - name: customAuth
        config:
          authorize_host: auth:3000
          authorize_path: /api/auth/authorize
          skipped_paths:
            - /api/ping
            - /api/impots/ping
            - /api/caf/ping
            - /api/etudiant/ping
  - name: introspect
    url: http://auth:3000/api/auth/authorize
    plugins:
      - name: customAuth
        config:
          authorize_host: auth:3000
          authorize_path: /api/auth/authorize
      - name: response-transformer
        config:
          remove:
            json:
              - _id
    routes:
      - name: introspect
        paths:
          - /api/introspect
  - name: admin
    url: http://auth:3000/admin
    routes:
      - name: admin
        paths:
          - /admin
