_format_version: "1.1"

services:
  - name: website
    url: https://betagouv.github.io/api-particulier-web/
    routes:
      - name: home
        paths:
          - /
  - name: api-particulier
    url: http://api-particulier:3004/api
    routes:
      - name: api
        paths:
          - /api
    plugins:
      - name: customAuth
        config:
          authorize_host: auth:3000
          authorize_path: /api/auth/authorize
          skipped_paths:
            - /api/ping
            - /api/impots/ping
            - /api/caf/ping
            - /api/etudiant/ping
  - name: introspect
    url: http://auth:3000/api/auth/authorize
    plugins:
      - name: response-transformer
        config:
          remove:
            json:
              - _id
    routes:
      - name: introspect
        paths:
          - /api/introspect
  - name: admin
    url: http://auth:3000/admin
    routes:
      - name: admin
        paths:
          - /admin

plugins:
  - name: ip-restriction
    config:
      whitelist:
        - 172.19.0.1
  - name: rate-limiting
    config:
      policy: local
      second: 20
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
      headers:
        - Accept
        - Content-Length
        - Content-Type
        - X-API-Key
        - X-User
      exposed_headers:
        - X-API-Key
      credentials: true
      max_age: 3600
